package io.livekit.android.example.voiceassistant

const val sandboxID = ""
const val hardcodedUrl = "wss://aisha-bj4wst6w.livekit.cloud"
const val hardcodedToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6ImFpc2hhLXJvb20iLCJjYW5QdWJsaXNoIjp0cnVlLCJjYW5TdWJzY3JpYmUiOnRydWUsImNhblB1Ymxpc2hEYXRhIjp0cnVlfSwic3ViIjoibW9iaWxlLXVzZXIiLCJpc3MiOiJBUElzSGo0dXRMNGNpR0siLCJuYmYiOjE3ODIyMTI5ODEsImV4cCI6MTc4NDgwNDk4MX0.19uCO47G2vyg-HiJB3HMXagke5cFOB7kqsbP-JuprF4"
const val agentName = "my-agent"